#!/usr/bin/env bash

img="$1"
col="$2"
line="$3"
width="$4"
height="$5"

# When running inside Neovim terminal, we need unicode-placeholder mode
# This works in terminal programs that don't support kitty graphics protocol
if [ -n "$TMUX" ]; then
    # Use passthrough for tmux (automatically enables unicode-placeholder)
    kitty +kitten icat --passthrough=tmux --place="${width}x${height}@0x0" "$img"
else
    # Use unicode-placeholder for display within Neovim terminal
    kitty +kitten icat --unicode-placeholder --place="${width}x${height}@0x0" "$img"
fi

