#!/usr/bin/env bash

img="$1"
col="$2"
line="$3"
width="$4"
height="$5"

# Detect if we're running in tmux
if [ -n "$TMUX" ]; then
    # Use passthrough for tmux
    kitty +kitten icat --passthrough=tmux --place="${width}x${height}@0x0" --scale-up "$img"
else
    # Direct display without tmux passthrough
    kitty +kitten icat --place="${width}x${height}@0x0" --scale-up "$img"
fi

